services:
  dev:
    build: ./nuxt
    ports:
      - "3000:3000"
    volumes:
      - ./nuxt:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  preview:
    build: ./nuxt
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
