version: '3.8'
services:
  dev:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./nuxt:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  preview:
    build: .
    command: npm run preview
    volumes:
      - ./nuxt:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
