name: test and deploy

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check browserslist
        run: npx browserslist@latest

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run generate

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
        working-directory: ./
      - run: npm run generate
        working-directory: ./
      - run: npm install -g firebase-tools
      - run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
        working-directory: ./
