name: test

on:
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: nuxt/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./nuxt

      - name: Check browserslist
        run: npx browserslist@latest
        working-directory: ./nuxt

      - name: Lint
        run: npm run lint
        working-directory: ./nuxt

      - name: Build
        run: npm run generate
        working-directory: ./nuxt
