name: test

on:
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Work Directory Change
        run: cd nuxt
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: nuxt/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check browserslist
        run: npx browserslist@latest

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run generate
